manager: Azmathulla Khan
teamroom: Eng.UnitTest
units: 
    - unit: https://jira.devfactory.com/browse/TA-392
automation:
    product agnostic: true
    product specific: 
        ##- product name: !!str #product names
    description: This will auto generate the template code with necessary fixture class and test functions for all the functions of the given class. In them we will have all the parameter initialization and the Action part (function calling with parameter) of the Test functions.
    effort: 7
    impact: 10% Productivity improvement in C++ HUT team.
