manager: José Martins
teamroom: Eng.Feature.QE
units:
    - unit: https://jira.devfactory.com/browse/ARCH-1522
automation:
    product agnostic: true
    product specific:
        - product name: N/A
    description: Automatically restrict transition on Jira, if tickets are on the wrong status.
    effort: 1
    impact: 0.8
