manager: Carlos Eduardo Witte
teamroom: Eng.DevSpacesImport
units: 
    - unit: https://app.crossover.com/x/dashboard/team/2678/1661414/team-metrics
automation: 
    product agnostic: yes
    product specific: 
        - product name: null
    description: VSCode plugin to hide DevSpaces overhead and improve the developers experience.
    effort: 61
    impact: 0.40