manager: !!str #<manager name>
teamroom: !!str #<teamroom name>
units: !!seq
    - unit: !!str #<link>
automation: !!map
    product agnostic: !!bool #boolean
    product specific: !!seq
        - product name: !!str #product names
    description: !!str
    effort: !!int #days
    impact: !!float #<%> at teamroom level